name: Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.zabiyka }}
          password: ${{ secrets.pJbezy50! }}

      - name: Build Docker image
        run: docker build -t plehov_java311-java-app:latest .

      - name: Push Docker image
        run: docker push plehov_java311-java-app:latest
